name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-10.15, windows-2019]

    steps:
    - uses: actions/checkout@v2

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{ runner.workspace }}/build

    - name: Configure CMake
      working-directory: ${{ runner.workspace }}/build
      # Uses Git's included Bash on Windows
      shell: bash
      run: cmake $GITHUB_WORKSPACE -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: ctest --build-config "${BUILD_TYPE}" --output-on-failure

    - name: Archive artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: hello-${{ matrix.os }}
        path: |
          ${{ runner.workspace }}/build/hello*
